import Head from 'next/head'
import Form from '../components/Form/Form'
import Posts from '../components/Posts/Posts'


import {Provider} from 'react-redux';
// import {applyMiddleware, compose} from 'redux';
import { configureStore } from '@reduxjs/toolkit'
// import thunk from 'redux-thunk';
import reducers from '../reducers';


const store = configureStore({reducer: reducers})

export default function Home() {
  return (
    <Provider store={store}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Form />
        <Posts />
      </div>
    </Provider>
  )
}
